SMM_STRUCTURE = {
    "A": ["General Rules"],
    "B": [
        "Preliminaries",
        "Preliminary particulars",
        "Contracts particulars",
        "General matters",
        "Temporary works",
        "Works by public bodies",
        "Works by nominated sub-contractors",
        "Goods and materials from nominated suppliers",
        "Protecting and cleaning the works",
        "Contingencies",
    ],
    "C": [
        "Demolitions and Alterations",
        "General to Section C",
        "Demolitions",
        "Alterations",
        "Sundries",
    ],
    "D": [
        "Excavations and Earthwork",
        "Generally to Section D",
        "Site preparation",
        "Excavation",
        "Disposal of water",
        "Planking and strutting",
        "Hardcore filling",
    ],
    "E": [
        "Piling",
        "Generally to Section E",
        "Wood or concrete piles",
        "Contractor-designed concrete piles",
        "Steel sheet piling",
    ],
    "F": [
        "Concrete Work",
        "Generally to Section F",
        "Plain concrete and reinforced concrete",
        "Reinforcement",
        "Formwork",
        "Precast concrete units",
        "Hollow block suspended Construction",
        "Prestressed concrete",
        "Precast prestressed units",
        "Sundries",
    ],
    "G": [
        "Walling",
        "Generally to Section G",
        "Walling in connection with boilers",
        "Facework",
        "Brick facework",
        "Rubble walling",
        "Masonry",
        "Cast stonework",
        "Clayware work",
        "Sundries",
        "Centering",
        "Damp-proof courses",
    ],
    "H": ["Underpinning", "Generally to Section H", "Work in all trades"],
    "J": ["Asphalt Work", "Generally to Section J", "Mastic asphalt"],
    "K": [
        "Roofing",
        "Generally to Section K",
        "Slate of tile roofing",
        "Corrugated or troughed sheet roofing",
        "Thatch roofing",
        "Roof decking",
        "Bitumen-felt roofing",
        "Sheet metal roofing",
        "Sheet metal flashings and gutter linings and metal trims",
    ],
    "L": [
        "Carpentry",
        "Generally to Section L",
        "Structural timbers",
        "Boarding",
        "Fillets grounds batterns and bracketing",
        "Sundries",
    ],
    "M": [
        "Joinery",
        "Generally to Section M",
        "Flooring",
        "Boarded or panelled linings, casing and partitions",
        "Doors, windows, skylights and lanterns",
        "Frames, sills and kerbs",
        "Fillets, glazing and beads and grounds",
        "Shelves, table-tops and seats",
        "Draining-boards and backboards",
        "Fittings and fixtures",
        "Staircases",
        "Standard units",
        "Sundries",
        "Ironmongery",
    ],
    "N": [
        "Structural Steelwork",
        "Generally to Section N",
        "Grillages and girders",
        "Stanchions, columns and portal frames",
        "Roof members, braces, struts and rails",
        "Sundries",
    ],
    "P": [
        "Metal Work",
        "Generally to Section P",
        "Work in plates, bars, section and tubes",
        "Work in sheet metal",
        "Work in wire mesh or expanded metal",
        "Compose units",
        "Standard units",
        "Sundries",
    ],
    "Q": [
        "Plumbing and Engineering Installations",
        "Generally to Section Q",
        "Gutterwork",
        "Pipework",
        "Ductwork",
        "Equipment",
        "Thermal insulation",
        "Builders work",
    ],
    "R": [
        "Mechanical Engineering Installation",
        "Generally to Section R",
        "Piped Systems",
        "Conveying installations",
        "Ductwork",
    ],
    "S": [
        "Electrical Installation",
        "Generally to Section S",
        "Equipment and control gear",
        "Conduits, trunking and tray",
        "Cables and conductors",
        "Fittings and accessories",
        "Sundries",
        "Builder’s work",
        "Protection",
    ],
    "T": [
        "Floor, Wall and Ceiling Finishes",
        "Generally to Section T",
        "In-situ finishings",
        "Tile, slab or block finishings",
        "Plain sheet finishings",
        "Beds and backings",
        "Lathing and baseboarding",
        "Suspended plain sheet linings with supporting metal work",
        "Self-finished partitions",
    ],
    "U": [
        "Glazing",
        "Generally to Section U",
        "Glass in openings",
        "Leaded lights and copper lights in openings",
        "Patent glazing",
        "Dome-lights",
    ],
    "V": [
        "Painting and Decorating",
        "Generally to Section V",
        "Painting and similar work",
        "Polishing",
        "Sign writing",
    ],
    "W": ["Drainage", "Generally to Section W", "Work in all trades"],
    "X": ["Landscaping", "Generally to Section X"],
    "Y": ["Roadworks", "Generally to Section Y"],
    "Z": [
        "Fencing",
        "Generally to Section Z",
        "Opening-type fencing",
        "Close-type fencing",
        "Gates",
    ],
}
